add test case GetMatchingMethod_WithRpcRoute and bufix
edjCase/JsonRpc pull request #88
Opened 2020-09-10 20:00 UTC by 2m0nd

Hi, i found bug, when two controllers has similar methods (name and parameters). 
Method DefaultRequestMatcher.FilterAndBuildMethodInfoByRequest get from cache other MethodInfo (first invoked) for execution action.

I write example solution for this bug, please review and approve or fix this bug more best.

2020-09-13 00:41 UTC, Gekctek requested changes
Classic cache issue. This works but for my own weird reasons, i want the RpcRequestSignature to only be based off the request object rather than putting in the path also. I think this can just be solved by tweaking what you did to remove the path from the sig and change the cache dict to be a dict in a dict 
```private static ConcurrentDictionary<RpcRequestSignature, RpcMethodInfo[]> requestToMethodCache { get; } = ...
```
would turn into something like
```private static ConcurrentDictionary<RpcPath, ConcurrentDictionary<RpcRequestSignature, RpcMethodInfo[]>> requestToMethodCache { get; } =...
```
Or something combining the two there vs changing the sig object

2020-09-14 17:46 UTC, 2m0nd commented
Change cache type to ConcurrentDictionary<RpcPath?, ConcurrentDictionary<RpcRequestSignature, RpcMethodInfo[]>> and fix method FilterAndBuildMethodInfoByRequest.

2020-09-14 20:25 UTC, Gekctek approved these changes

2020-09-14 20:25 UTC, merged

2020-09-14 20:27 UTC, Gekctek commented
https://www.nuget.org/packages/EdjCase.JsonRpc.Router/4.1.0