Add auth in documentation/feature and fix method grouping in documentation by declaring type
edjCase/JsonRpc pull request #90
Opened 2020-09-24 10:15 UTC by 2m0nd

2020-09-29 02:58 UTC, Gekctek commented
What is the declaring type for? We might need to approach it a different way. The controller type/name isnt used as an identifier always. I think it needs to be more abstract. Ill take a look

2020-09-29 03:03 UTC, Gekctek commented
ya it looks like it defaults to using the controller prefix or controller name but can be overridden. 

Maybe I dont understand what its used for, but i dont want the DeclaringType to be used. What is the OpenApiTag Name?

2020-09-29 18:25 UTC, 2m0nd commented
DeclaringType (controller type) for access to  controller type xml annotation.
https://github.com/edjCase/JsonRpc/blob/d496f02f9c5dd4beb5e8af7531a67d54c95072c6/test/EdjCase.JsonRpc.Router.Sample/ComplexExampleController.cs#L9-L13
Methods will be grouped by this annotation.
https://user-images.githubusercontent.com/2101501/93918916-76169f00-fd26-11ea-9e71-f06140e0ceea.png

2020-09-29 23:39 UTC, Gekctek commented
The only abstract concept we have are path to the methods and the methods. The idea of grouping methods besides using the path dont exist. We can add something but it isnt part of the spec. I know the controllers are there but they are not required/are abstracted out. Do we need this grouping? Can we just do it based on path? Because most of the time path+controller are the same anyways

2020-09-30 05:57 UTC, 2m0nd commented
This feature allows not only grouping, but also makes it possible to describe the group with a friendly name in the documentation. this is useful when you can tell the front-end developer the friendly name of a method group.
An example of a small project:
![image](https://user-images.githubusercontent.com/2101501/94648082-3134ce80-030b-11eb-8e02-1130887219b9.png)

2020-09-30 17:27 UTC, Gekctek commented
In order to do this we will need to add another property to the configuration when adding methods/controllers. We can default it to be grouped by the controller name but not have it depend on it. Can we do without it and then add it in another PR?

2020-09-30 19:28 UTC, 2m0nd commented
This feature can wait, I am still using my fork and so far I have implemented getting a description of the controller from xml documentation as in this PR, but I will wait for such an opportunity in your original project.

2020-10-20 10:37 UTC, 2m0nd commented
The xml documentation requires complete information about the method. I have added SourceMethodInfo in the local fork so far.
https://github.com/edjCase/JsonRpc/pull/90/files#diff-7da23c1ccd420bcfd9d2177eb699c6710a210d4bb3bc644aa74ba14ced316d4dR30

Method annotation:
https://github.com/edjCase/JsonRpc/pull/90/files#diff-5071ee65e4bd6622ed8275acd54e2ae0345a997b887fd2ce227c3255b7ab3e62R51-R52

Controller annotation:
https://github.com/edjCase/JsonRpc/pull/90/files#diff-99cf8148084e5ad3f30bad0a35cf6400980abee8c344221c570ad0b0dbe15d08R134

2020-11-03 01:09 UTC, Gekctek requested changes

2020-11-03 01:09 UTC, Gekctek commented on src/EdjCase.JsonRpc.Router/Abstractions/IRpcMethodProvider.cs
> +		MethodInfo SourceMethodInfo { get; }
This won't work either. I have abstracted out the MethodInfo and am using `IRpcMethodInfo` in its place. If we want this we need to have some custom object/string to represent what the declaring type is

2021-01-16 20:38 UTC, closed without merging